# Generated by Django 6.1 on 2026-08-16 15:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opponent_name', models.CharField(max_length=150)),
                ('competition', models.CharField(blank=True, max_length=200)),
                ('played_at', models.DateTimeField()),
                ('best_of', models.PositiveSmallIntegerField(choices=[(3, 'Best of 3'), (5, 'Best of 5'), (7, 'Best of 7')], default=5)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=20)),
                ('player_sets_won', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('opponent_sets_won', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to=settings.AUTH_USER_MODEL)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_player', to='players.player')),
            ],
            options={
                'ordering': ['-played_at', '-created_at'],
                'indexes': [models.Index(fields=['owner', '-played_at'], name='matches_mat_owner_i_097607_idx'), models.Index(fields=['owner', 'status'], name='matches_mat_owner_i_1d0a98_idx'), models.Index(fields=['player', '-played_at'], name='matches_mat_player__e980de_idx')],
            },
        ),
    ]
