# Generated by Django 6.1 on 2026-09-16 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0006_prepare_authorized_review_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClosedTestInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_digest', models.CharField(max_length=64, unique=True)),
                ('redeemed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='subscription',
            name='closed_test_ends_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
