# Generated by Django 6.1 on 2026-08-24 21:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0002_player_world_and_national_ranking'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('competition_type', models.CharField(choices=[('LEAGUE', 'League'), ('TOURNAMENT', 'Tournament'), ('CHAMPIONSHIP', 'Championship'), ('CUP', 'Cup'), ('OTHER', 'Other')], default='TOURNAMENT', max_length=20)),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('ACTIVE', 'In progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PLANNED', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('season', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitions', to=settings.AUTH_USER_MODEL)),
                ('players', models.ManyToManyField(blank=True, related_name='competitions', to='players.player')),
            ],
            options={
                'ordering': ['start_date', 'name'],
                'indexes': [models.Index(fields=['owner', 'start_date'], name='competition_owner_i_aaa59d_idx'), models.Index(fields=['owner', 'status'], name='competition_owner_i_4f5aee_idx')],
            },
        ),
    ]
