# Generated by Django 6.1 on 2026-08-23 22:15

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('INCOME', 'Income'), ('EXPENSE', 'Expense')], max_length=10)),
                ('area', models.CharField(choices=[('PERSONAL', 'Personal'), ('PROFESSIONAL', 'Professional')], max_length=15)),
                ('category', models.CharField(choices=[('HOUSING', 'Housing'), ('FOOD', 'Food'), ('TRANSPORT', 'Transport'), ('HEALTH', 'Health'), ('EDUCATION', 'Education'), ('LEISURE', 'Leisure'), ('SUBSCRIPTIONS', 'Subscriptions'), ('TAXES', 'Taxes'), ('TOURNAMENT_FEES', 'Tournament fees'), ('TRAINING', 'Training'), ('COACHING', 'Coaching'), ('TRAVEL', 'Travel'), ('HOTEL', 'Hotel'), ('EQUIPMENT', 'Equipment'), ('CLUB_FEES', 'Club fees'), ('FEDERATION_FEES', 'Federation fees'), ('RECOVERY', 'Medical / recovery'), ('MARKETING', 'Marketing'), ('COURSES', 'Courses'), ('SPONSORSHIP', 'Sponsorship'), ('PRIZE_MONEY', 'Prize money'), ('SALARY', 'Salary'), ('OTHER', 'Other')], max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=255)),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('DEBIT_CARD', 'Debit card'), ('CREDIT_CARD', 'Credit card'), ('BANK_TRANSFER', 'Bank transfer'), ('DIGITAL_WALLET', 'Digital wallet'), ('OTHER', 'Other')], default='BANK_TRANSFER', max_length=20)),
                ('status', models.CharField(choices=[('PAID', 'Paid'), ('PENDING', 'Pending')], default='PAID', max_length=10)),
                ('is_recurring', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
